name: Terraform Deploy (OIDC)

on:
  workflow_dispatch:
    inputs:
      tf_directory:
        description: "Terraform directory to deploy."
        required: true
        default: "./terraform-storage-account"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Deploy Terraform
    runs-on: ubuntu-latest

    environment: dev   # optional: use protected environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.2

      - name: Login to Azure via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}        # GitHub secret for App Registration client ID
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}        # GitHub secret for tenant ID
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} # optional if needed
          auth_type: oidc
          #allow-no-subscriptions: true
          #use_oidc: true
          #enable-oidc: true

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./${{ github.event.inputs.tf_directory }}

      # Validate configuration
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./${{ github.event.inputs.tf_directory }}

      # Create execution plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./${{ github.event.inputs.tf_directory }}

      # Apply (only if manual trigger)
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./${{ github.event.inputs.tf_directory }}
